### ISSUE TITLE
Dependencies don't support Node > 5

### ISSUE THREAD

**Issue by mathew-kurian** [qimingweng/react-modal-dialog#38]
Additionally `narcissus` is not declared in package.json

**Comment by qimingweng** [comment]
Addressed in 7c4a2b2af42b09462f91e7185248abb7d7dccf42

What do you mean don't support node > 5 though?

**Comment by mathew-kurian** [comment]
Your latest push should resolve the issue. Previously, some dependencies performed a engine check during install which enforced node version <= 5. Thanks for the push

**Comment by qimingweng** [comment]
Weird, maybe it was the JSS dependencies since I didn't see that error just now

**Comment by dtipson** [comment]
I'm on v6.9.1 and seeing `npm WARN react-jss@2.1.1 requires a peer of jss@>=1.0.0 < 5.0.0 but none was installed.` though that's odd, as that's not the version of react-jss specified in the dependencies, but no other module I have seems to use react-jss.  The version of react-jss is behind the current 5.x.x one though.

**Comment by qimingweng** [comment]
Try updating to the latest react modal dialog. It no longer depends on jss at all!

On Sat, Dec 10, 2016 at 10:47 PM Drew

<
mailto:Drew <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I'm on v6.9.1 and seeing

npm WARN react-jss@2.1.1 requires a peer of jss@>=1.0.0 < 5.0.0 but none was installed.

though that's odd, as that's not the version of react-jss specified in the dependencies, but no other module I have seems to use react-jss. The version of react-jss is behind the current 5.x.x one though.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/qimingweng/react-modal-dialog/issues/38#issuecomment-266258865
, or

**Comment by dtipson** [comment]
I still see the warning even on a fresh repo, and it's definitely set to 4.0.2.  It's weird, it's definitely not listed as a dependency in package.json, but..

└─┬ react-modal-dialog@4.0.2 
  ├─┬ active-event-stack@1.0.0 
  │ └── lodash@3.10.1 
  ├── classnames@2.2.5 
  ├── dynamics.js@1.1.5 
  ├── immutable@3.8.1 
  ├── UNMET PEER DEPENDENCY jss@>=1.0.0 < 5.0.0
  ├── keycode@2.1.7 
  ├── lodash@3.10.1 
  ├─┬ narcissus@1.0.0 
  │ └─┬ inline-style-prefixer@2.0.5 
  │   ├── bowser@1.6.0 
  │   └── hyphenate-style-name@1.0.2 
  ├── react-center-component@3.0.0 
  └─┬ react-jss@2.1.1 
    └── hoist-non-react-statics@1.1.0

**Comment by qimingweng** [comment]
Ah I see, there was an extraneous `react-jss`. Removed and fixed in 4.0.3
